### ISSUE TITLE
Comparing  Goehash w21z76281 

### ISSUE THREAD

**Issue by ppKrauss** [akhenakh/CompareGeoHashvsS2#1]
Hi, a suggestion, to compare same cell of ~5x5 meters with other popular geocoding grid systems, as [drafting here](https://wiki.openstreetmap.org/wiki/Geohash).

Suppose a cell of ~5x5 meters how to compare S2 with PlusCode, Geohash, etc. in "address code" applications?  The stable polygon of reference is a country, state or city (e.g. Singapura in the   w21z76281 example), so we can remove the "prefix" (the `w2` in the Geohash example)...  So, what the "full S2 address" and the "city S2 address" of this 5x5 cell?  

PS: by [s2cell_statistics](https://s2geometry.io/resources/s2cell_statistics) need perhaps cell ~22  to a 5x5 square address... So, it is a "22 digits" code?

**Comment by akhenakh** [comment]
s2 ids are not meant to be human readable, but to be used as indexes by computer.

The levels are explained here https://s2geometry.io/devguide/

**Comment by ppKrauss** [comment]
Oops, sorry (!)... I was browsing to a interesting new ideia without read in deep about it.  Let's change the suggestion from "show how-to" to *"can I try?"*...  

I can delete the issue, perhaps the correct is to restart with a better question in the mailing list... Well, to stay here, let's restart in a game of words: 

* *"three words, ..., to identify one of 57 trillion 3 x 3 m squares on the earth's surface. This doesn't seem that great ..."*, J.D.

* *"S2 Cells... Every cm2 on Earth can be represented using a 64-bit integer"*, E. V.

Can I try gain, starting to check  the clues left by the big picture?

------

> s2 ids are not meant to be human readable, but to be used as indexes by computer.

The S2 cells are 64-bit integers, so can be a human readable string with base10 or [base36](https://en.wikipedia.org/wiki/Base36)... 

One important application for indexes like Geohash, is to be adapted to  express addresses in a kind of  ~5x5m  grid. A 9-characters Geohash is also a 64-bit integer and it is not very human-readable: human need a shorter code, and the adaptation is to taking off the common prefix of all addresses of some region.  In the example of Singapore's Merlion (`w21z76281`) the prefix is `w2`, so not a big gain, the remaining `1z76281` is yet not-so-pretty for humans.

Others as [PlusCode](https://en.wikipedia.org/wiki/Open_Location_Code) or [Mapcode](https://en.wikipedia.org/wiki/Mapcode) have more sucess tham Geohash doing it. Mapcode for instance enforces official standards (the administrative boundary polygon and its BBOX) to obtain better compression.  Using the official [ISO code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3) `SGP` of Singapore and its BBOX, Mapcode compressed to 4 characters (`NPPZ`)...   This *"use some container polygon as reference"* strategy seems possible with S2...

There are some clues that we can check before to say that will be impossible with S2:

1. It is possible to obtain S2 leafCell-ID with "more zeros" (less entropy) when the spatial scale   (level) is bigger? ... I am supposing that there are "more zeros" at km scale cell ID tham in a cm scale cell ID. 

2. It is possible to preserve "same prefix" (or something similar for the S2 code structure) for  neighbor cells? 

3. As all cells are contained into the same city-polygon (or BBOX or etc.), there are an operation with this container that result in "more zero bits" in the 64-bit integer?  Some kind of subtraction? (any kind... perhaps no obvious one as [Minkowski operations](https://en.wikipedia.org/wiki/Minkowski_addition))

PS: perhaps we need  a specific database (real world dataset) to discuss the behaviour of the "zeros" in the S2 IDs.
